# Generated by Django 2.2 on 2020-11-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Live'), (2, 'Pending'), (3, 'Archived')])),
            ],
            options={
                'ordering': ['-launch_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('task_type', models.PositiveSmallIntegerField(choices=[(1, 'Survey'), (2, 'Discussion'), (3, 'Diary')])),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.Tile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
