# Generated by Django 2.2 on 2020-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='launch_date',
            field=models.DateTimeField(),
        ),
    ]
